### ISSUE TITLE
ttrss::enable_update_daemon does not enable the service

### ISSUE THREAD

**Issue by nhinds** [jpds/puppet-ttrss#1]
In the version on the forge and the current version in `master`, setting `ttrss::enable_update_daemon` doesn't work.

The version on the forge tries to read a global variable `$::enable_update_daemon`, and the version in `master` reads the variable `$ttrss::params::enable_update_daemon`, which is hardcoded to `false`. It should either read the class parameter `$ttrss::enable_update_daemon` or be given the parameter by the main `ttrss` class.

**Comment by jpds-zz** [comment]
I've merged your change into master, thanks for the patch!
